// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqmGKAU7qZJUfLUNFJUiUvE_WM1JrN61w',
    appId: '1:152045168761:web:f15c2a6296e23c962d8ca8',
    messagingSenderId: '152045168761',
    projectId: 'test1final-9a0b5',
    authDomain: 'test1final-9a0b5.firebaseapp.com',
    storageBucket: 'test1final-9a0b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6Qd5IsfL120Mr44NExPw3U_L3ksVDkc',
    appId: '1:152045168761:android:a52b7c60234cbffa2d8ca8',
    messagingSenderId: '152045168761',
    projectId: 'test1final-9a0b5',
    storageBucket: 'test1final-9a0b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfOx5JyodkRcml35clSpbZrINzCiogFo',
    appId: '1:152045168761:ios:d7e75fa19a4bbfa12d8ca8',
    messagingSenderId: '152045168761',
    projectId: 'test1final-9a0b5',
    storageBucket: 'test1final-9a0b5.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlfOx5JyodkRcml35clSpbZrINzCiogFo',
    appId: '1:152045168761:ios:5ed7050b1de57af32d8ca8',
    messagingSenderId: '152045168761',
    projectId: 'test1final-9a0b5',
    storageBucket: 'test1final-9a0b5.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
